-d C:\Gowin\Projetos\vga\vga\impl\gwsynthesis\vga.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Gowin\Projetos\vga\vga\src\lcd.cst
-cfg C:\Gowin\Projetos\vga\vga\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
