-d D:\repos\LCD_Demo_tang_nano_1k\Demo3_ascii\impl\gwsynthesis\vga.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst D:\repos\LCD_Demo_tang_nano_1k\Demo3_ascii\src\lcd.cst
-cfg D:\repos\LCD_Demo_tang_nano_1k\Demo3_ascii\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
