-d C:\Users\fpfir\OneDrive\Documentos\GitHub\LCD_Demo_tang_nano_1k\Demo2_moving_square\impl\gwsynthesis\vga.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\fpfir\OneDrive\Documentos\GitHub\LCD_Demo_tang_nano_1k\Demo2_moving_square\src\lcd.cst
-cfg C:\Users\fpfir\OneDrive\Documentos\GitHub\LCD_Demo_tang_nano_1k\Demo2_moving_square\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
